version: '1.0'

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres
  server:
    depends_on:
      - postgresdb
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$POSTGRESDB_HOST
      - DB_USER=$POSTGRESDB_USER
      - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - DB_NAME=$POSTGRESDB_DATABASE
      - DB_PORT=$POSTGRESDB_DOCKER_PORT
    stdin_open: true
    tty: true
  client:
    build:
      context: ./client
    image: expo-react-native
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - $CLIENT_LOCAL_PORT:$CLIENT_DOCKER_PORT
    environment:
      - EXPO_DEVTOOLS_LISTEN_PORT=19002
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    stdin_open: true
    tty: true

volumes:
  db: